import Head from 'next/head'
import { Inter } from '@next/font/google'
import Test1 from 'components/Test1'
import Test2 from 'components/Test2'
import Test3 from 'components/Test3'
import Test4 from 'components/Test4'

const inter = Inter({ subsets: ['latin'] })



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='scroll-smooth
      snap-mandatory snap-y 
      h-[100vh] overflow-y-auto  '
      >
        <Test1/>
        <Test2/>
        <Test3/>
        <Test4/>
      </div>
    </>
  )
}
